### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-module-template-http#2]
Thanks for starting this.  Some possible improvements:
- [ ] Add some common README text. Probably using the https://github.com/RichardLitt/standard-readme format we've used elsewhere.
- [x] `test/` has copies of top-level files.  Remove the cruft.
- [ ] Add a `logger` in `lib/http.js` or via a `lib/logger.js`.
- [ ] Should we use a `bedrock-` prefix for the config namepace like `bedrock-MODULE-http`?  (Probably shouldn't say `profile` as it does now.)
- [ ] Perhaps in all the files, change module name to `bedrock-MODULE-http` or `bedrock-FIXME-http` so it's a bit easier to see what to update.
- [ ] Should the template repo naming pattern be `bedrock-module-template-http`?  Or would a common `-template` suffix work better? `bedrock-module-http-template`, `bedrock-module-template`, `bedrock-web-module-template` etc.
